version: '2'
# NOTE: move this answer file up a directory so it'll work

services:

  personal_blog:
    image: personal_blog
    build: .
    ports:
      - "8080:8080"
    networks:
      - blog

networks:
  blog:
